baseurl = "/"
title = "Prometheus Workshop"

enableGitInfo = true

theme = ["docsy-puzzle", "docsy-plus", "docsy"]

languageCode = "en-us"

contentDir = "content/en"

[minify]
disableSVG = true

# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"


# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"


[Languages]
[Languages.en]
title = "Prometheus Workshop"
languageName = "English"
weight = 1


# navigation
[Languages.en.menu]

[[Languages.en.menu.main]]
weight = 3
name = "Puzzle ITC GmbH"
url = "https://www.puzzle.ch"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    LineNos = true
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "monokai"
    # Do not uncomment because it has an impact on the copy button. Fenced code blocks w/o syntax highlighting don't
    # have a copy button to visualize output of a command.
    # guessSyntax = "true"

[params]
copyright = "Puzzle ITC GmbH"
github_repo = "https://github.com/puzzle/prometheus-labs"
github_branch = "main"
imagePrefix = "puzzle_"
enabledModule = "base"
modeSwitcher = "true"

[params.replaceContent]
allowedHrefHosts = ['localhost', 'puzzle.ch', 'acend.ch']

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST"
queryParam = "h"
defaultValue = "http://localhost"
href = true

[[params.replaceContent.placeholders]]
placeholder = "<namespace>"
queryParam = "n"
defaultValue = "<namespace>"

# Enable Lunr.js offline search
offlineSearch = true

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/puzzle/prometheus-labs"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/puzzleitc"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/puzzle-itc/"
