baseurl = "/"
title = "Prometheus Basics Training"

enableGitInfo = true

languageCode = "en-us"

contentDir = "content/en"

[minify]
disableSVG = true

# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[Languages]
[Languages.en]
title = "Prometheus Basics Training"
languageName = "English"
weight = 1

# navigation
[Languages.en.menu]

[[Languages.en.menu.main]]
weight = 10
name = "acend gmbh"
url = "https://www.acend.ch"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style = "monokai"
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  # guessSyntax = "true"

[params]
copyright = "acend gmbh"
github_repo = "https://github.com/puzzle/prometheus-training"
github_branch = "main"

enabledModule = "base baloise"
modeSwitcher = "true"
distroName = "OpenShift"
cliToolName = "oc"

# use those placeholder params to replace the content when the component don't run under the same url
# eg. set prometheus to LOCALHOST_PROM alertmanager to LOCALHOST_ALERT and the pass different query params to replace the values individually 
[params.replacePlaceholder]
prometheus = "LOCALHOST_PROM"
thanos = "LOCALHOST_THANOS"
thanosquerier = "LOCALHOST_QUERIER"
alertmanager = "LOCALHOST_ALERT"
mailcatcher = "LOCALHOST_MAIL_CATCHER"
grafana = "LOCALHOST_GRAFANA"
git = "LOCALHOST_GIT"
openshift_console = "LOCALHOST_OPENSHIFT"
k8sPrometheus = "LOCALHOST:19090"
k8sAlertmanager = "LOCALHOST:19093"
k8sGrafana = "LOCALHOST:13000"

[params.replaceContent]
allowedHrefHosts = ['localhost', 'puzzle.ch', 'acend.ch', 'balgroupit.com']

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST_PROM"
queryParam = "h"
defaultValue = "https://localhost_prom"
href = true

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST_ALERT"
queryParam = "a"
defaultValue = "https://localhost_alert"
href = true

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST_GRAFANA"
queryParam = "g"
defaultValue = "https://localhost_grafana"
href = true

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST_THANOS"
queryParam = "th"
defaultValue = "https://localhost_thanos"
href = true

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST_QUERIER"
queryParam = "tq"
defaultValue = "https://localhost_querier"
href = true

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST_GIT"
queryParam = "git"
defaultValue = "https://localhost_git"
href = true

[[params.replaceContent.placeholders]]
placeholder = "http://LOCALHOST_OPENSHIFT"
queryParam = "ocp"
defaultValue = "https://localhost_openshift"
href = true

[[params.replaceContent.placeholders]]
placeholder = "<namespace>"
queryParam = "n"
defaultValue = "<namespace>"

[[params.replaceContent.placeholders]]
placeholder = "<team>"
queryParam = "t"
defaultValue = "<team>"

# Enable Lunr.js offline search
offlineSearch = true

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/puzzle/prometheus-training"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/acendch"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/acendch/"


[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
  [[module.imports]]
    path = "github.com/acend/docsy-acend"
    disable = false
  [[module.imports]]
    path = "github.com/acend/docsy-plus"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
