acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: puzzle
      replicaCount: 1
      image:
        repository: quay.io/puzzle/prometheus-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        useDefaultSecret: true
        appname: prometheus-training
        domainmain: puzzle.ch
        domain: k8s.puzzle.ch
    - 
      name: acend
      replicaCount: 1
      image:
        repository: quay.io/puzzle/prometheus-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-acend"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard 
        appname: prometheus-basics
        domain: training.acend.ch
    - 
      name: baloise
      replicaCount: 1
      image:
        repository: quay.io/puzzle/prometheus-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-baloise"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard 
        appname: prometheus-basics-baloise
        domain: training.acend.ch



nameOverride: "prometheus-basics"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
