---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: example-web-python-probe
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc:19115
  targets:
    staticConfig:
      static:
        - example-web-python.application-metrics.svc:5000/health
