apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    prometheus-monitoring: 'true'
  name: loki
spec:
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki
  type: NodePort